### ISSUE TITLE
AnimatedSizeAndFade.showHide in AnimatedSizeAndFade.showHide

### ISSUE THREAD

**Issue by Lomski** [marcglasberg/animated_size_and_fade#2]
Hi, I'm using this package to show/hide some lists of items. And it works great for single depth. However, if  i put AnimatedSizeAndFade.showHide in AnimatedSizeAndFade.showHide it still works, but with some issues. When i open second (inner) list, animation bounce a litle. Loks like that because of AnimatedSwitcher. Any ideas how i can fix it?

**Comment by marcglasberg** [comment]
Whenever you have an animation inside of another you may have some bouncing problems. It depends on the exact effect you are trying to achieve. Most likely this is not something I can fix for you. I'd suggest you play with the Curve and Duration.
