### ISSUE TITLE
Scales Child When Using Card and CachedNetworkImage

### ISSUE THREAD

**Issue by zgosalvez** [marcglasberg/animated_size_and_fade#3]
## without CachedNetworkImage:
```dart
Card(
  color: Colors.white,
  child: AnimatedSizeAndFade(
    vsync: this,
    child: Container(color: Colors.green),
  ),
),
```
![Screen Shot 2020-07-23 at 18 05 27](https://user-images.githubusercontent.com/1798166/88275064-55729e80-cd0f-11ea-8557-33b5205a43e3.png)

## with CachedNetworkImage:
```dart
Card(
  color: Colors.white,
  child: AnimatedSizeAndFade(
    vsync: this,
    child: CachedNetworkImage(
      imageUrl: '...',
      fit: BoxFit.cover,
      color: Colors.red,
    ),
  ),
),
```
![Screen Shot 2020-07-23 at 18 06 20](https://user-images.githubusercontent.com/1798166/88275077-59062580-cd0f-11ea-9ea6-c2826ef8b4a1.png)

**Comment by marcglasberg** [comment]
@zgosalvez I'd suggest this is NOT a result of the `AnimatedSizeAndFade` widget. The answer to your question depends on the layout of the `CachedNetworkImage`. I suggest you read my article about layout: https://medium.com/flutter-community/flutter-the-advanced-layout-rule-even-beginners-must-know-edc9516d1a2
