### ISSUE TITLE
Unnecessary rebuild

### ISSUE THREAD

**Issue by krida2000** [marcglasberg/animated_size_and_fade#6]
Because of the `currentChild` placed in the `Container`, `currentChild` will be rebuilded one extra time.

```
children = [
          Positioned(
            left: 0.0,
            right: 0.0,
            child: Container(child: previousChildren[0]),
          ),
          Container(child: currentChild),
        ];
```

I tested it and without `Container` it works fine and doesnt cause unnecessary rebuild

**Comment by marcglasberg** [comment]
I don't really know why this `Container` was there. I removed it in version 3.0.1.

However, I also don't see why it would create an extra rebuild, as it seems to me it wouldn't make any difference. Can you explain why?

**Comment by krida2000** [comment]
As i understood it is because when `previousChildren` are not empty `currentChild` builds in `Container` and otherwise without `Container`. And flutter think that `Container(child: currentChild)` is not the same as just `currentChild` and builds a new one.

In my case inside `currentChild` was animation that was started twice because of extra rebuild.

```
if (currentChild != null) {
      if (previousChildren.isEmpty)
        children = [currentChild];
      else {
        children = [
          Positioned(
            left: 0.0,
            right: 0.0,
            child: Container(child: previousChildren[0]),
          ),
          Container(child: currentChild),
        ];
      }
    }
```
